from setuptools import setup

setup(
    name='Telegram',
    version='',
    packages=['venv.Lib.site-packages.attr', 'venv.Lib.site-packages.bson', 'venv.Lib.site-packages.cffi',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.lxml', 'venv.Lib.site-packages.lxml.html',
              'venv.Lib.site-packages.lxml.includes', 'venv.Lib.site-packages.lxml.isoschematron',
              'venv.Lib.site-packages.past', 'venv.Lib.site-packages.past.tests', 'venv.Lib.site-packages.past.types',
              'venv.Lib.site-packages.past.utils', 'venv.Lib.site-packages.past.builtins',
              'venv.Lib.site-packages.past.translation', 'venv.Lib.site-packages.zope.interface',
              'venv.Lib.site-packages.zope.interface.tests', 'venv.Lib.site-packages.zope.interface.common',
              'venv.Lib.site-packages.zope.interface.common.tests', 'venv.Lib.site-packages.isapi',
              'venv.Lib.site-packages.motor', 'venv.Lib.site-packages.motor.aiohttp',
              'venv.Lib.site-packages.motor.frameworks', 'venv.Lib.site-packages.motor.frameworks.asyncio',
              'venv.Lib.site-packages.motor.frameworks.tornado', 'venv.Lib.site-packages.w3lib',
              'venv.Lib.site-packages.future', 'venv.Lib.site-packages.future.moves',
              'venv.Lib.site-packages.future.moves.dbm', 'venv.Lib.site-packages.future.moves.html',
              'venv.Lib.site-packages.future.moves.http', 'venv.Lib.site-packages.future.moves.test',
              'venv.Lib.site-packages.future.moves.urllib', 'venv.Lib.site-packages.future.moves.xmlrpc',
              'venv.Lib.site-packages.future.moves.tkinter', 'venv.Lib.site-packages.future.tests',
              'venv.Lib.site-packages.future.types', 'venv.Lib.site-packages.future.utils',
              'venv.Lib.site-packages.future.builtins', 'venv.Lib.site-packages.future.backports',
              'venv.Lib.site-packages.future.backports.html', 'venv.Lib.site-packages.future.backports.http',
              'venv.Lib.site-packages.future.backports.test', 'venv.Lib.site-packages.future.backports.email',
              'venv.Lib.site-packages.future.backports.email.mime', 'venv.Lib.site-packages.future.backports.urllib',
              'venv.Lib.site-packages.future.backports.xmlrpc', 'venv.Lib.site-packages.future.standard_library',
              'venv.Lib.site-packages.gridfs', 'venv.Lib.site-packages.parsel', 'venv.Lib.site-packages.pyasn1',
              'venv.Lib.site-packages.pyasn1.type', 'venv.Lib.site-packages.pyasn1.codec',
              'venv.Lib.site-packages.pyasn1.codec.ber', 'venv.Lib.site-packages.pyasn1.codec.cer',
              'venv.Lib.site-packages.pyasn1.codec.der', 'venv.Lib.site-packages.pyasn1.codec.native',
              'venv.Lib.site-packages.pyasn1.compat', 'venv.Lib.site-packages.scrapy',
              'venv.Lib.site-packages.scrapy.core', 'venv.Lib.site-packages.scrapy.core.downloader',
              'venv.Lib.site-packages.scrapy.core.downloader.handlers', 'venv.Lib.site-packages.scrapy.http',
              'venv.Lib.site-packages.scrapy.http.request', 'venv.Lib.site-packages.scrapy.http.response',
              'venv.Lib.site-packages.scrapy.xlib', 'venv.Lib.site-packages.scrapy.utils',
              'venv.Lib.site-packages.scrapy.loader', 'venv.Lib.site-packages.scrapy.contrib',
              'venv.Lib.site-packages.scrapy.contrib.loader', 'venv.Lib.site-packages.scrapy.contrib.spiders',
              'venv.Lib.site-packages.scrapy.contrib.exporter', 'venv.Lib.site-packages.scrapy.contrib.pipeline',
              'venv.Lib.site-packages.scrapy.contrib.linkextractors',
              'venv.Lib.site-packages.scrapy.contrib.spidermiddleware',
              'venv.Lib.site-packages.scrapy.contrib.downloadermiddleware', 'venv.Lib.site-packages.scrapy.spiders',
              'venv.Lib.site-packages.scrapy.commands', 'venv.Lib.site-packages.scrapy.selector',
              'venv.Lib.site-packages.scrapy.settings', 'venv.Lib.site-packages.scrapy.contracts',
              'venv.Lib.site-packages.scrapy.pipelines', 'venv.Lib.site-packages.scrapy.templates.project.module',
              'venv.Lib.site-packages.scrapy.templates.project.module.spiders',
              'venv.Lib.site-packages.scrapy.extensions', 'venv.Lib.site-packages.scrapy.contrib_exp',
              'venv.Lib.site-packages.scrapy.contrib_exp.downloadermiddleware',
              'venv.Lib.site-packages.scrapy.linkextractors', 'venv.Lib.site-packages.scrapy.spidermiddlewares',
              'venv.Lib.site-packages.scrapy.downloadermiddlewares', 'venv.Lib.site-packages.automat',
              'venv.Lib.site-packages.automat._test', 'venv.Lib.site-packages.certifi',
              'venv.Lib.site-packages.OpenSSL', 'venv.Lib.site-packages.pymongo', 'venv.Lib.site-packages.twisted',
              'venv.Lib.site-packages.twisted.tap', 'venv.Lib.site-packages.twisted.web',
              'venv.Lib.site-packages.twisted.web.test', 'venv.Lib.site-packages.twisted.web._auth',
              'venv.Lib.site-packages.twisted.cred', 'venv.Lib.site-packages.twisted.cred.test',
              'venv.Lib.site-packages.twisted.mail', 'venv.Lib.site-packages.twisted.mail.test',
              'venv.Lib.site-packages.twisted.pair', 'venv.Lib.site-packages.twisted.pair.test',
              'venv.Lib.site-packages.twisted.test', 'venv.Lib.site-packages.twisted.conch',
              'venv.Lib.site-packages.twisted.conch.ui', 'venv.Lib.site-packages.twisted.conch.ssh',
              'venv.Lib.site-packages.twisted.conch.test', 'venv.Lib.site-packages.twisted.conch.client',
              'venv.Lib.site-packages.twisted.conch.insults', 'venv.Lib.site-packages.twisted.conch.scripts',
              'venv.Lib.site-packages.twisted.conch.openssh_compat', 'venv.Lib.site-packages.twisted.names',
              'venv.Lib.site-packages.twisted.names.test', 'venv.Lib.site-packages.twisted.trial',
              'venv.Lib.site-packages.twisted.trial.test', 'venv.Lib.site-packages.twisted.trial._dist',
              'venv.Lib.site-packages.twisted.trial._dist.test', 'venv.Lib.site-packages.twisted.words',
              'venv.Lib.site-packages.twisted.words.im', 'venv.Lib.site-packages.twisted.words.test',
              'venv.Lib.site-packages.twisted.words.xish', 'venv.Lib.site-packages.twisted.words.protocols',
              'venv.Lib.site-packages.twisted.words.protocols.jabber', 'venv.Lib.site-packages.twisted.logger',
              'venv.Lib.site-packages.twisted.logger.test', 'venv.Lib.site-packages.twisted.python',
              'venv.Lib.site-packages.twisted.python.test', 'venv.Lib.site-packages.twisted.runner',
              'venv.Lib.site-packages.twisted.runner.test', 'venv.Lib.site-packages.twisted.spread',
              'venv.Lib.site-packages.twisted.spread.test', 'venv.Lib.site-packages.twisted.plugins',
              'venv.Lib.site-packages.twisted.scripts', 'venv.Lib.site-packages.twisted.scripts.test',
              'venv.Lib.site-packages.twisted._threads', 'venv.Lib.site-packages.twisted._threads.test',
              'venv.Lib.site-packages.twisted.internet', 'venv.Lib.site-packages.twisted.internet.test',
              'venv.Lib.site-packages.twisted.internet.iocpreactor', 'venv.Lib.site-packages.twisted.persisted',
              'venv.Lib.site-packages.twisted.persisted.test', 'venv.Lib.site-packages.twisted.protocols',
              'venv.Lib.site-packages.twisted.protocols.test', 'venv.Lib.site-packages.twisted.protocols.haproxy',
              'venv.Lib.site-packages.twisted.protocols.haproxy.test', 'venv.Lib.site-packages.twisted.enterprise',
              'venv.Lib.site-packages.twisted.application', 'venv.Lib.site-packages.twisted.application.test',
              'venv.Lib.site-packages.twisted.application.twist',
              'venv.Lib.site-packages.twisted.application.twist.test',
              'venv.Lib.site-packages.twisted.application.runner',
              'venv.Lib.site-packages.twisted.application.runner.test', 'venv.Lib.site-packages.twisted.positioning',
              'venv.Lib.site-packages.twisted.positioning.test', 'venv.Lib.site-packages.adodbapi',
              'venv.Lib.site-packages.hamcrest', 'venv.Lib.site-packages.hamcrest.core',
              'venv.Lib.site-packages.hamcrest.core.core', 'venv.Lib.site-packages.hamcrest.core.helpers',
              'venv.Lib.site-packages.hamcrest.library', 'venv.Lib.site-packages.hamcrest.library.text',
              'venv.Lib.site-packages.hamcrest.library.number', 'venv.Lib.site-packages.hamcrest.library.object',
              'venv.Lib.site-packages.hamcrest.library.collection',
              'venv.Lib.site-packages.hamcrest.library.integration', 'venv.Lib.site-packages.queuelib',
              'venv.Lib.site-packages.queuelib.tests', 'venv.Lib.site-packages.telegram',
              'venv.Lib.site-packages.telegram.ext', 'venv.Lib.site-packages.telegram.files',
              'venv.Lib.site-packages.telegram.games', 'venv.Lib.site-packages.telegram.utils',
              'venv.Lib.site-packages.telegram.inline', 'venv.Lib.site-packages.telegram.vendor',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.util',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.contrib',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages.backports',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.telegram.payment', 'venv.Lib.site-packages.telegram.passport',
              'venv.Lib.site-packages.win32com', 'venv.Lib.site-packages.win32com.test',
              'venv.Lib.site-packages.win32com.demos', 'venv.Lib.site-packages.win32com.client',
              'venv.Lib.site-packages.win32com.makegw', 'venv.Lib.site-packages.win32com.server',
              'venv.Lib.site-packages.win32com.servers', 'venv.Lib.site-packages.cssselect',
              'venv.Lib.site-packages.hyperlink', 'venv.Lib.site-packages.hyperlink.test',
              'venv.Lib.site-packages.pycparser', 'venv.Lib.site-packages.pycparser.ply',
              'venv.Lib.site-packages.pythonwin.pywin', 'venv.Lib.site-packages.pythonwin.pywin.mfc',
              'venv.Lib.site-packages.pythonwin.pywin.idle', 'venv.Lib.site-packages.pythonwin.pywin.Demos.ocx',
              'venv.Lib.site-packages.pythonwin.pywin.tools', 'venv.Lib.site-packages.pythonwin.pywin.dialogs',
              'venv.Lib.site-packages.pythonwin.pywin.docking', 'venv.Lib.site-packages.pythonwin.pywin.debugger',
              'venv.Lib.site-packages.pythonwin.pywin.framework',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor.color',
              'venv.Lib.site-packages.pythonwin.pywin.scintilla', 'venv.Lib.site-packages.asn1crypto',
              'venv.Lib.site-packages.asn1crypto._perf', 'venv.Lib.site-packages.constantly',
              'venv.Lib.site-packages.pydispatch', 'venv.Lib.site-packages.exampleproj',
              'venv.Lib.site-packages.incremental', 'venv.Lib.site-packages.incremental.tests',
              'venv.Lib.site-packages.libfuturize', 'venv.Lib.site-packages.libfuturize.fixes',
              'venv.Lib.site-packages.win32comext.adsi', 'venv.Lib.site-packages.win32comext.bits',
              'venv.Lib.site-packages.win32comext.mapi', 'venv.Lib.site-packages.win32comext.shell',
              'venv.Lib.site-packages.win32comext.axdebug', 'venv.Lib.site-packages.win32comext.ifilter',
              'venv.Lib.site-packages.win32comext.propsys', 'venv.Lib.site-packages.win32comext.axscript',
              'venv.Lib.site-packages.win32comext.axscript.client',
              'venv.Lib.site-packages.win32comext.axscript.server', 'venv.Lib.site-packages.win32comext.internet',
              'venv.Lib.site-packages.win32comext.axcontrol', 'venv.Lib.site-packages.win32comext.directsound',
              'venv.Lib.site-packages.win32comext.directsound.test', 'venv.Lib.site-packages.win32comext.authorization',
              'venv.Lib.site-packages.win32comext.taskscheduler', 'venv.Lib.site-packages.cryptography',
              'venv.Lib.site-packages.cryptography.x509', 'venv.Lib.site-packages.cryptography.hazmat',
              'venv.Lib.site-packages.cryptography.hazmat.backends',
              'venv.Lib.site-packages.cryptography.hazmat.backends.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.bindings',
              'venv.Lib.site-packages.cryptography.hazmat.bindings.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.primitives',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.kdf',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.asymmetric',
              'venv.Lib.site-packages.libpasteurize', 'venv.Lib.site-packages.libpasteurize.fixes',
              'venv.Lib.site-packages.pyasn1_modules', 'venv.Lib.site-packages.service_identity',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations', 'PostGatherer.PostGatherer',
              'PostGatherer.PostGatherer.spiders'],
    url='',
    license='',
    author='Bismarck',
    author_email='',
    description=''
)
